defaults:
  - _self_
  - task: halfcheetah-medium-expert-v2

pipeline_name: dql_d4rl_mujoco
mode: inference
seed: 0
device: cuda:0

# Environment
normalize_reward: True
discount: 0.99

# Actor
solver: ddpm
diffusion_steps: 5
sampling_steps: 5
predict_noise: True
ema_rate: 0.995
actor_learning_rate: 0.0003
training_num_particles: 16
inference_num_particles: 50
itr_num: 10
svgd_step: 0.1

# Critic
hidden_dim: 256
critic_learning_rate: 0.0003
alpha: 0.2


# Training
gradient_steps: 500000
batch_size: 256
ema_update_interval: 5
log_interval: 1000
save_interval: 100000
inference_interval: 5000

# Inference
ckpt: latest
num_envs: 50
num_episodes: 3
num_candidates: 50
temperature: 0.5
use_ema: True

# hydra
hydra:
  job:
    chdir: false

